---
# Handler to handle common notifications. Handlers are called by other plays.
# See http://docs.ansible.com/playbooks_intro.html for more information about handlers.

- name: reload ganglia
  service:
   name: 'gmond'
   state: 'reloaded'

- name: restart firewalld
  service:
   name: firewalld
   state: restarted

- name: restart ntp
  service: name=ntpd state=restarted

- name: restart iptables
  service: name=iptables state=restarted

