---
# This playbook contains play to prepare the system and upgrade StorNext FC-client on RHEL7 workstations and servers  

#- debug: var=stornext_5_4_0_rpms_path #verbosity=

- name: Get installed current StorNext version BEFORE upgrade
  shell: "/opt/quantum/snupdate/bin/snupdate show versions | awk '/.*\\(Current.*\\)$/ {print $2}'"
  register: stornext_curr_inst

- debug: msg="BEFORE upgrade:SN version {{ stornext_curr_inst.stdout }} is installed on {{ ansible_host }}!" verbosity=0

#- debug: var=stornext_curr_inst verbosity=2


# # Ref http://downloads.quantum.com/StorNext5/5.4/6-68044-01_RevK_StorNext_5_StorNext_FX_5_Upgrade_Guide.pdf 
- name: Import a StorNext package into repository and upgrade (from /astro/local/maint/...)
  shell: >
    "test -d {{ stornext_5_4_0_rpms_path }} && 
    /opt/quantum/snupdate/bin/snupdate import {{ stornext_5_4_0_rpms_path }} &&
    /opt/quantum/snupdate/bin/snupdate upgrade snfs_client" 
  when: "stornext_vers_curr in stornext_curr_inst.stdout"
#    echo " test -d {{ stornext_5_4_0_rpms_path }} && StorNext version {{ stornext_vers_curr }} is installed on {{ ansible_host }}!"

- name: Get installed current StorNext version AFTER upgrade
  shell: "/opt/quantum/snupdate/bin/snupdate show versions | awk '/.*\\(Current.*\\)$/ {print $2}'"
  register: stornext_curr_inst_after

- name: List installed current StorNext version AFTER upgrade
  debug: msg="AFTER upgrade:SN version {{ stornext_curr_inst_after.stdout }} is installed on {{ ansible_host }}!" verbosity=0


# - name: Test 1,2,3
#   yum: name={{ item }} state=present
#   with_items:
# #    - kernel-3.10.0-327.36.3.el7
#     - test-package
#   when: "stornext_vers_curr in stornext_curr_inst.stdout" 

