---
# tasks file for php
# Install Remi repo and install php 5.5
- name: remi repo install
  copy: src=remi.repo
        dest=/etc/yum.repos.d/
        owner=root group=root mode=0644

- name: php 5.5 install
  yum: name={{ item }} state=installed
       enablerepo=remi-php55
       with_items:
         - php
         - php-common
         - php-xml
         - php-mysqlnd
         - php-gd
         - php-json
         - php-mcrypt
         - php-intl
         - php-fpm
         - php-opcache
         - php-pecl-apcu
         - php-pecl-imagick
         - apcu-panel
         - mysqlnd-qc-panel
         

- name: start php-fpm service
  service: name={{ item}} state=started enabled=true
  with_items:
    - php-fpm
    
          
         