---
# This playbook will install necessary software for container hosts 

#- name: Install package
#  yum: name="{{ yum_pkgs_hosts_ct}}"  state=present
#  when: ansible_lsb.major_release == "8" and (ansible_lsb.id == "RedHatEnterpriseServer" or 
#    ansible_lsb.id == "CentOSStream" or ansible_lsb.id == "CentOS" or ansible_lsb.id == "Fedora")
#  tags: yum_pkgs_hosts_ct

# This playbook will test podman pods
- name: Test Podman MariaDB
  containers.podman.podman_play:
#    kube_file: /home/susinths/.ansible/wordpress_nginx-pod.yaml
    kube_file: /root/tmp/podman/wordpress/wordpress_mariadb_1.yaml
    state: started


 #- name: Test Podman Wordpress
 # containers.podman.podman_play:
#    kube_file: /home/susinths/.ansible/wordpress_nginx-pod.yaml
#    kube_file: /root/tmp/podman/wordpress/wordpress_wordpress_1.yaml
#    state: started

#- name: Start Fluentbit Podman container
#  containers.podman.podman_pod:
#    name: wordpressmariadb1
#    state: started


