---
# This role install Google Chrome repo and install Google Chrom on selected hosts  
- name: Install Google Chrome repo
  copy: dest=/etc/yum.repos.d/google-chrome.repo src=google-chrome.repo
  when: ansible_distribution_major_version == "7" and
  	ansible_distribution == "Red Hat Enterprise Linux Workstation"
  
- name: Install Google Chrome
  yum: name=google-chrome-stable state=present
  when: ansible_hostname == {{ item }}
  with_items:
  - "kitalpha"
  - "nishtya"