---
# This playbook tries to create desired state using declarations in the roles

- name: apply common configuration to all nodes
  hosts: all
  remote_user: root

  roles:
    - common

- name: Workstation nodes
  hosts: hosts_wks_headless, hosts_wks_gui
  remote_user: root

  roles:
    - workstation

- name: NAS box
  hosts: hosts_nas
  remote_user: root

  roles:
    - nas

- name: Container nodes
  hosts: containers_nodes
  remote_user: root

  roles:
    - container
    
- name: Hypervisor hosts
  hosts: hosts_virt
  remote_user: root

  roles:
    - virt
    


#
#- name: deploy MySQL and configure the databases
#  hosts: dbservers
#  remote_user: root
#
#  roles:
#    - db
