---
# These tasks install Nginx
- name: nginx repo install
  copy: src=nginx.repo
        dest=/etc/yum.repos.d/
        owner=root group=root mode=0644

- name: nginx install
  yum: name={{ item }} state=present
       enablerepo=nginx
  with_items:
    - nginx

- name: insert iptables rule for httpd
  lineinfile: dest=/etc/sysconfig/iptables create=yes state=present regexp="{{ httpd_port }}" insertafter="^:OUTPUT "
              line="-A INPUT -p tcp  --dport {{ httpd_port }} -j  ACCEPT"
  notify: restart iptables

- name: nginx service state
  service: name=nginx state=started enabled=yes

- name: Configure SELinux to allow httpd to connect to remote database
  seboolean: name=httpd_can_network_connect_db state=true persistent=yes 
  when: sestatus.rc != 0

#- name: Install nginx
#  yum: name={{ item }} state=present
#  with_items:
#   - httpd
#   - php
#   - php-mysql
#   - git
#   - libsemanage-python
#   - libselinux-python
