---
# This playbook configures some custom firewall..

- name: apply stornext_mdnetconfig to the nodes
  hosts: euclid_cluster:hercules_cluster:beehive_cluster 
  remote_user: root
  
  roles:
    - firewalld_lc_ufm
    
