---
# This playbook configures firewall ports for UFM

- name: apply stornext_mdnetconfig to the nodes
#  hosts: euclid_cluster:hercules_cluster
#  hosts: susin_hosts
  hosts: stornext_meta
  remote_user: root
  
  roles:
    - firewalld_meta
    #    - common
    #    - chrome
    
